### ISSUE TITLE
GLIBC_2.36 not found

### ISSUE THREAD

**Issue by walseb** [superherointj/nix-auto-gpt#5]
Hello!

I ran this today, and I'm getting an error that GLIBC_2.36 isn't found. Nixos 22.11 only has GLIBC_2.35, unfortunately.

I suppose the only way to fix it is to change my channels or to pull a version of nixpkgs with that version.

Thoughts?

Here's the error:
```
Traceback (most recent call last):
  File "/nix/store/rpri9nb8xpwwqakyrqbg8zdslkjs2hd3-python3-3.10.11/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nix/store/rpri9nb8xpwwqakyrqbg8zdslkjs2hd3-python3-3.10.11/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/admin/Downloads/Auto-GPT/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/nix/store/c424f8r8i3n7zyd11vzg59yw0d5xf0vn-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/c424f8r8i3n7zyd11vzg59yw0d5xf0vn-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/nix/store/c424f8r8i3n7zyd11vzg59yw0d5xf0vn-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/nix/store/c424f8r8i3n7zyd11vzg59yw0d5xf0vn-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/c424f8r8i3n7zyd11vzg59yw0d5xf0vn-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/nix/store/c424f8r8i3n7zyd11vzg59yw0d5xf0vn-python3.10-click-8.1.3/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/admin/Downloads/Auto-GPT/autogpt/cli.py", line 77, in main
    from autogpt.agent.agent import Agent
  File "/home/admin/Downloads/Auto-GPT/autogpt/agent/__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "/home/admin/Downloads/Auto-GPT/autogpt/agent/agent.py", line 3, in <module>
    from autogpt.app import execute_command, get_command
  File "/home/admin/Downloads/Auto-GPT/autogpt/app.py", line 23, in <module>
    from autogpt.commands.image_gen import generate_image
  File "/home/admin/Downloads/Auto-GPT/autogpt/commands/image_gen.py", line 9, in <module>
    from PIL import Image
  File "/nix/store/73a1dapyrngbi11rarfw73q73xdnqlxs-python3.10-pillow-9.4.0/lib/python3.10/site-packages/PIL/Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: /nix/store/vnwdak3n1w2jjil119j65k8mw1z23p84-glibc-2.35-224/lib/libc.so.6: version `GLIBC_2.36' not found (required by /nix/store/wbbj294s0gvk2282zy0brc8k3vxr3nrm-libXdmcp-1.1.3/lib/libXdmcp.so.6)

```

**Comment by superherointj** [comment]
Nixpkgs Stable does not have all dependencies necessary to run Auto-GPT. DuckDuckGo-Search being one I remember missing. I suggest you use unstable.

**Comment by walseb** [comment]
I see, thanks!
